-- Inserciones para tabla EMPLEADOS
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('12345678A', 'Roger', '26-35', 'Francia', 'VENTAS', 'PRESENCIAL');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('87654321B', 'Carlos López', '36-45', 'México', 'RECURSOS_HUMANOS', 'HIBRIDO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('56789012C', 'Ana Rodríguez', '18-25', 'Argentina', 'VENTAS', 'REMOTO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('34567890D', 'Javier Pérez', '46-55', 'Colombia', 'MARKETING', 'PRESENCIAL');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('78901234E', 'Laura Martínez', '+55', 'Chile', 'IT', 'HIBRIDO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('23456789F', 'Elena Sánchez', '26-35', 'España', 'RECURSOS_HUMANOS', 'REMOTO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('98765432G', 'Miguel Torres', '36-45', 'México', 'VENTAS', 'PRESENCIAL');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('87654321H', 'Sofía Ramírez', '46-55', 'España', 'MARKETING', 'HIBRIDO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('76543210I', 'Diego Fernández', '+55', 'España', 'IT', 'REMOTO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('65432109J', 'Lucía Moreno', '18-25', 'Chile', 'CONTABILIDAD', 'PRESENCIAL');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('54321098K', 'Pedro Suárez', '26-35', 'España', 'VENTAS', 'REMOTO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('43210987L', 'Carmen Vidal', '36-45', 'México', 'IT', 'HIBRIDO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('32109876M', 'Fernando Ruiz', '46-55', 'Argentina', 'RECURSOS_HUMANOS', 'PRESENCIAL');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('21098765N', 'Isabel Prieto', '+55', 'Colombia', 'MARKETING', 'REMOTO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('10987654O', 'Hugo Méndez', '18-25', 'Chile', 'CONTABILIDAD', 'HIBRIDO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('99887766P', 'Andrea Castro', '26-35', 'España', 'VENTAS', 'REMOTO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('88776655Q', 'Luis Vázquez', '36-45', 'México', 'IT', 'PRESENCIAL');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('77665544R', 'Natalia Peña', '46-55', 'Argentina', 'RECURSOS_HUMANOS', 'HIBRIDO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('66554433S', 'Alberto Navarro', '+55', 'Bolivia', 'MARKETING', 'REMOTO');
INSERT INTO EMPLEADOS (DNI, NOMBRE, EDAD, NACIONALIDAD, DEPARTAMENTO, MODALIDAD) VALUES ('55443322T', 'Sara Ortega', '18-25', 'Bolivia', 'CONTABILIDAD', 'PRESENCIAL');

